### ISSUE TITLE
Validate based on other fields

### ISSUE THREAD

**Issue by alochschmied** [copleykj/Mesosphere#41]
Is there a way to register your own format and have access to other field values? If not is there a plan to add this feature?

We have a collection for Countries and subdocumnets with States (for some of the Countries). We would like to make State mandatory (in user registration) if the chosen Country has States in our lookup collection.

We'd also love to be able to make State field mandatory if Country has States. In other words, implement our own, dynamic "mandatory function" again based on multiple field values.

**Comment by Tolmark12** [comment]
Or an account creation scenario where two passwords fields need to be checked to ensure match.

**Comment by copleykj** [comment]
@Tolmark12 see #56 for checking fields to see if one field equals another.

**Comment by Tolmark12** [comment]
Haha, just worked this out and submitted a pull request before seeing [#56]https://github.com/copleykj/Mesosphere/issues/56

**Comment by Tolmark12** [comment]
See pull request : #59

**Comment by copleykj** [comment]
Merged
