### ISSUE TITLE
Is there anyway to validate password confirmation field?

### ISSUE THREAD

**Issue by plm-tuongvan-pham** [copleykj/Mesosphere#56]
Like the title said, is there anyway the require depend on must equal to another field?

**Comment by copleykj** [comment]
There isn't a built in rule currently that handles this case but you can extend the rules using Mesosphere.registerRule() and create just about any rule one could think of.

```javascript
Mesosphere.registerRule("equalsField", function(fieldValue, ruleValue, fieldName, formFieldsObject){
    return fieldValue === formFieldsObject[ruleValue];
});
```
